### ISSUE TITLE
Error detecting itself?

### ISSUE THREAD

**Issue by furicle** [pmario/file-backups#11]
![image](https://user-images.githubusercontent.com/45774/33090093-c855a08c-cec0-11e7-8bdb-ffdeb173481c.png)

After a complete system reboot (Windows Updates)

Note this is with version 0.1.2 - may no longer apply
Only one copy in add-ons, and it doesn't show as disabled?

**Comment by pmario** [comment]
That's interesting. .. I'll check :)

**Comment by pmario** [comment]
Could you reproduce the issue with the latest version?

I'll post 0.3.0 soon. Would be interesting, to see what's going on there.

**Comment by pmario** [comment]
I don't know, how to reproduce this message?

Do you use TWclassic?

**Comment by pmario** [comment]
I did see this once, ... but I can't replicate it properly. ...

**Comment by frankJMH** [comment]
Same problem here, same error message on opening the TW file :-(
All worked fine up to March 3rd (date of my last save and backup), no idea what changed then. I am using TWclassic. Reverted back to File Backups 0.3.1 but that has the same problem.

**Comment by pmario** [comment]
>All worked fine up to March 3rd (date of my last save and backup), no idea what changed then.

March 3rd ... nothing happened from the plugin side. .. Did you try to restart the browser?

**Comment by pmario** [comment]
@frankJMH ... Do you know, what you did, when the info happened

**Comment by frankJMH** [comment]
hello pmario, on 3rd March from my end nothing changed that I remember (no Win or FireFox updates, I have the latest FF 58.0.2 (64-bit))
In the meantime I removed all extension from Firefox, refreshed Firefox and when that didnt help also uninstalled +reinstalled Firefox with only the "File Backups" plugin -but unfortunately the problem remains..

**Comment by pmario** [comment]
That's strange. ... Can you test the following steps.

 - Can you disable file-backups plugin
 - Load your TWclassic file 
 - right click - View page source
 - With ctrl-F search for:   tiddlyfox-message-box

You should _NOT_ find something. .. If you do, we have a problem

**Comment by frankJMH** [comment]
actually I found "tiddlyfox-message-box", in the last line..

**Comment by frankJMH** [comment]
..checked a few more backed up files -and found one earlier on 3rd March that opens without problems while "File Backups" enabled _and_ does not contain "tiddlyfox-message-box".
The next backup raises the problem and contains "tiddlyfox-message-box"..
Have we found the problem here?

**Comment by pmario** [comment]
>.. Have we found the problem here?

Yes. I'm not sure, how it happens, but it seems a temporary structure has been saved. ... 

The tiddlyfox-message-box is used to communicate between TW and the AddOn. .. It is created at startup.   BJ and I did implement a check, that allows us to detect each others AddOn. ... 

 - Which version of file-backups do you use. ... Try the latest version

----

 - **So first off all: create a backup of your file.**
 - open the file with a text editor
 - search for `<div id="tiddlyfox-message-box" style="display: none;" data-message-box-creator="file-backups"></div>` at the end of the file
 - delete it. 
 - save 
 - and try to reload the stuff with the browser. 
 - file backups should work again

**Comment by frankJMH** [comment]
OK, did above. Now my corrected TW file loads fine while "File Backups" enabled.

"File Backups" works, however after saving a modified tiddler it opens the "save as" window and asks permission to overwrite itself.
The same happens with the next backup file.

Note that I do have a good backup, so I can also recover manually from there. But I'm also happy to continue debugging, let me know what your prefer.

**Comment by pmario** [comment]
You have to have your files saved to the browser "Downloads" directory or a sub-directory. We are not allowed anymore to freely save where we want.

**Comment by pmario** [comment]
You may need to do a browser restart in between, so every tab  and the addon are re-initialized. ... Just to be sure

**Comment by pmario** [comment]
@furicle ... Did you have a problem with TWclassic or TW5??

**Comment by frankJMH** [comment]
Restarted my PC, but the "save as" dialogue continues coming up.
The location of my TW file (and the "twBackups" under it) is the same as when all worked fine, and in the "Downloads" folder (via a hard link to another location).
I tested with the file in "Downloads" proper (without hardlink) and again the same problem. In fact, in this case the first time it "save as" to "beakon.tmp.html".

**Comment by frankJMH** [comment]
Found it: its because a Firefox setting "Always ask you where to save files". If I change that to "Save files to: Downloads" it all works fine (guess that changed because of Firefox reinstall)..
So, now I continue using your excellent tool! Thanks for the help.

**Comment by ppmt** [comment]
I will write here since the issue is still open.
I am using your plugin and until today I had no issue with it. I use it to save and backup to of my own tiddlywiki.

Tonight I downloaded a copy of mGSD (old MonkeyGTD) and copied in the same place as the other wiki I have.

For some reason it complains of detecting another instance of the plugin

**Comment by pmario** [comment]
The next version of the plugin will have a better check. ... That's why it's still open.

@ppmt Did you check this: https://github.com/pmario/file-backups/issues/11#issuecomment-372019791 info?

**Comment by ppmt** [comment]
Hello. I will wait for the next version then :)

And no I had not seen this specific message. So I followed it and the error message has disappeared which is good but instead each time I open the file I get the following window that pops up

It appears that this TiddlyWiki has been incorrectly saved. Please see http://www.tiddlywiki.com/#Download for details

once I click OK it seems fine and the file loads. I can live with that so all is good!

**Comment by pmario** [comment]
>once I click OK it seems fine and the file loads. I can live with that so all is good!

I'm not sure here. ... How did you download the mGSD? 

You know, there is a TW5 version which is called: [cardo.wiki](http://cardo.wiki/)

**Comment by ppmt** [comment]
I downloaded it from the website: http://mgsd.tiddlyspot.com/#mGSD

I was not aware of Cardo.wiki...will check

Thanks

**Comment by pmario** [comment]
IMO should be fixed with V0.3.10-beta pls test: https://github.com/pmario/file-backups/releases/tag/V0.3.10-beta

**Comment by pmario** [comment]
Got feedback at: https://github.com/pmario/file-backups/issues/28#issuecomment-525700584 

Pretty sure we found all the problems now. closing this one.

**Comment by Mark-Booth** [comment]
This just happened to me today.

Following advice earlier, I closed Firefox, edited the tiddlyfox-message-box out of the html, restarted Firefox and the error went away. I then made a trivial change to the tiddlywiki, saved it, tried to reload the page to verify that the changes had been saved, and the "another plugin" error came back.

Looking at the source again I see the tiddlyfox-message-box was back in the file.

Firefox 68.3.0esr, File Backups 0.3.5, TiddlyWiki cassic

**Comment by Mark-Booth** [comment]
Installing File Backups 0.3.10 beta, I can confirm that it no longer pops up the message box, but it doesn't remove the tiddlyfox-message-box div from tiddlywiki html file on save however.

Editing the file manually, then saving again doesn't add it back in though.

How far are we from 0.3.10 coming out of beta and being uploaded to the Mozilla add-on store? It would be nice if the update were done automatically.

Thanks for your work on this addon, and if there is anything I can do to help getting 0.3.10 out of beta, please ask.

**Comment by pmario** [comment]
@Mark-Booth Hi, Thanks for the info. I'll try to activate 0.3.10 very soon. I didn't get much feedback on problems with 0.3.5. ... that's why I did hesitate to change it.
